### ISSUE TITLE
Nice Project! Whats the licence?

### ISSUE THREAD

**Issue by Mr-Philipp** [thitiblog/ws2812b-raspberry-pi2#4]
Hi!

Your project caught my attention because its working flawlessly on the pi 3 and seems to be really light weight. Sadly you did not add any licence. I would love to use your code in other projects but according to the github guidlines it itsnt allowed. 

Please consider adding a licence like [MIT](https://choosealicense.com/licenses/mit/#suggest-this-license)

Thank you :)

**Comment by mrthiti** [comment]
I add license in commit https://github.com/thiti-y/ws2812b-raspberry-pi2/commit/c13e299d3fc3be423f8a2f4a0d89d312c9b79baa
